---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: perconapgclusters.pg.percona.com
spec:
  group: pg.percona.com
  names:
    kind: PerconaPGCluster
    listKind: PerconaPGClusterList
    plural: perconapgclusters
    singular: perconapgcluster
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          x-kubernetes-preserve-unknown-fields: true
        status:
          properties:
            state: { type: string }
            message: { type: string }
          type: object
          x-kubernetes-preserve-unknown-fields: true
      type: object