apiVersion: pgv2.percona.com/v2
kind: PerconaPGRestore
metadata:
  name: restore1
  finalizers:
  - percona.com/delete-restore
spec:
  pgCluster: cluster1
  repoName: repo1
#  options:
#  - --type=time
#  - --target="2022-11-30 15:12:11+03"
